---
title: "Big Data na Pratica"
author: "Ivanildo Batista"
date: "2 de marco de 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Instalando as bibliotecas

Pacotes usados
```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(scales)
library(data.table)
library(dtplyr)
```

Importando a base de dados
```{r}
df = fread('C:/Users/junio/TemperaturasGlobais.csv')
df #base de dados
```

Criando um subset dos dados
```{r}
CidadesBrasil = subset(df, Country=='Brazil')
CidadesBrasil = na.omit(CidadesBrasil) #eliminando os valores missing
```

```{r}
head(CidadesBrasil) #primeiras linhas da base de dados
nrow(df) #número de linha da base original
nrow(CidadesBrasil) #número de linha da nova base de dados
dim(CidadesBrasil) #dimensões da nova base de dados
```

Preparacao e organizacao dos dados
```{r}
#alterando o formato dos dados
CidadesBrasil$dt = as.POSIXct(CidadesBrasil$dt,format = '%Y-%m-%d')
```

```{r}
#criando nova coluna de meses
CidadesBrasil$Month = month(CidadesBrasil$dt)
```

```{r}
#criando nova coluna de anos
CidadesBrasil$Year = year(CidadesBrasil$dt)
```
Carregando Subsets da capitais do Nordeste

```{r}
#Maranhão (MA) - São Luís
slu = subset(CidadesBrasil, City='São Luís')
slu = subset(slu, Year %in% c(1796,1846,1896,1946,1996,2012))
```

```{r}
#Piauí (PI) - Teresina
pia = subset(CidadesBrasil, City='Teresina')
pia = subset(pia, Year %in% c(1796,1846,1896,1946,1996,2012))
```

```{r}
#Ceará (CE) - Fortaleza
forta = subset(CidadesBrasil, City='Fortaleza')
forta = subset(forta, Year %in% c(1796,1846,1896,1946,1996,2012))
```

```{r}
#Rio Grande do Norte (RN) - Natal
nat = subset(CidadesBrasil, City='Natal')
nat = subset(nat, Year %in% c(1796,1846,1896,1946,1996,2012))
```

```{r}
#Paraíba (PB) - João Pessoa
jpes = subset(CidadesBrasil, City='João Pessoa')
jpes = subset(jpes, Year %in% c(1796,1846,1896,1946,1996,2012))
```

```{r}
#Pernambuco (PE) - Recife
recf = subset(CidadesBrasil, City='Recife')
recf = subset(recf, Year %in% c(1796,1846,1896,1946,1996,2012))
```

```{r}
#Alagoas (AL) - Maceió
mace = subset(CidadesBrasil, City='Maceió')
mace = subset(mace, Year %in% c(1796,1846,1896,1946,1996,2012))
```

```{r}
#Sergipe (SE) - Aracaju
arac = subset(CidadesBrasil, City='Aracaju')
arac = subset(arac, Year %in% c(1796,1846,1896,1946,1996,2012))
```

```{r}
#Bahia (BA) - Salvador
salv = subset(CidadesBrasil, City='Salvador')
salv = subset(salv, Year %in% c(1796,1846,1896,1946,1996,2012))
```


**CRIANDO GRAFICOS PARA SERIE DE TEMPERATURA DE CADA CAPITAL**

```{r}
p_slu = ggplot(slu, aes(x=Month, y=AverageTemperature, color=as.factor(Year)))+
  geom_smooth(se=FALSE, fill=NA, size=2)+
  theme_light(base_size = 20)+
  xlab("Mês")+
  ylab("Temperatura Média")+
  scale_color_discrete(" ")+
  ggtitle("Temperatura média ao longo dos anos em São Luís")+
  theme(plot.title = element_text(size=18))
```

```{r}
p_pia = ggplot(pia, aes(x=Month, y=AverageTemperature, color=as.factor(Year)))+
  geom_smooth(se=FALSE, fill=NA, size=2)+
  theme_light(base_size = 20)+
  xlab("Mês")+
  ylab("Temperatura Média")+
  scale_color_discrete(" ")+
  ggtitle("Temperatura média ao longo dos anos em Teresina")+
  theme(plot.title = element_text(size=18))
```

```{r}
p_forta = ggplot(forta, aes(x=Month, y=AverageTemperature, color=as.factor(Year)))+
  geom_smooth(se=FALSE, fill=NA, size=2)+
  theme_light(base_size = 20)+
  xlab("Mês")+
  ylab("Temperatura Média")+
  scale_color_discrete(" ")+
  ggtitle("Temperatura média ao longo dos anos em Fortaleza")+
  theme(plot.title = element_text(size=18))
```

```{r}
p_nat = ggplot(nat, aes(x=Month, y=AverageTemperature, color=as.factor(Year)))+
  geom_smooth(se=FALSE, fill=NA, size=2)+
  theme_light(base_size = 20)+
  xlab("Mês")+
  ylab("Temperatura Média")+
  scale_color_discrete(" ")+
  ggtitle("Temperatura média ao longo dos anos em Natal")+
  theme(plot.title = element_text(size=18))
```

```{r}
p_jpes = ggplot(jpes, aes(x=Month, y=AverageTemperature, color=as.factor(Year)))+
  geom_smooth(se=FALSE, fill=NA, size=2)+
  theme_light(base_size = 20)+
  xlab("Mês")+
  ylab("Temperatura Média")+
  scale_color_discrete(" ")+
  ggtitle("Temperatura média ao longo dos anos em João Pessoa")+
  theme(plot.title = element_text(size=18))
```


```{r}
p_recf = ggplot(recf, aes(x=Month, y=AverageTemperature, color=as.factor(Year)))+
  geom_smooth(se=FALSE, fill=NA, size=2)+
  theme_light(base_size = 20)+
  xlab("Mês")+
  ylab("Temperatura Média")+
  scale_color_discrete(" ")+
  ggtitle("Temperatura média ao longo dos anos em Recife")+
  theme(plot.title = element_text(size=18))
```

```{r}
p_mace = ggplot(mace, aes(x=Month, y=AverageTemperature, color=as.factor(Year)))+
  geom_smooth(se=FALSE, fill=NA, size=2)+
  theme_light(base_size = 20)+
  xlab("Mês")+
  ylab("Temperatura Média")+
  scale_color_discrete(" ")+
  ggtitle("Temperatura média ao longo dos anos em Maceió")+
  theme(plot.title = element_text(size=18))
```


```{r}
p_arac = ggplot(arac, aes(x=Month, y=AverageTemperature, color=as.factor(Year)))+
  geom_smooth(se=FALSE, fill=NA, size=2)+
  theme_light(base_size = 20)+
  xlab("Mês")+
  ylab("Temperatura Média")+
  scale_color_discrete(" ")+
  ggtitle("Temperatura média ao longo dos anos em Aracajú")+
  theme(plot.title = element_text(size=18))
```

```{r}
p_salv = ggplot(salv, aes(x=Month, y=AverageTemperature, color=as.factor(Year)))+
  geom_smooth(se=FALSE, fill=NA, size=2)+
  theme_light(base_size = 20)+
  xlab("Mês")+
  ylab("Temperatura Média")+
  scale_color_discrete(" ")+
  ggtitle("Temperatura média ao longo dos anos em Salvador")+
  theme(plot.title = element_text(size=18))
```

Imprimindo os graficos

```{r}
p_slu
p_pia
p_forta
p_nat
p_jpes
p_recf
p_mace
p_arac
p_salv
```