---
title: "Graficos (Introducao)"
author: "Ivanildo Batista"
date: "10 de marco de 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introducao a graficos no R

Demonstracao de graficos
```{r}
demo('graphics')
```

Criando variaveis e gerando um grafico simples
```{r}
x = 5:14
y = 17:26
plot(x,y)
```

Com vetores
```{r}
altura = c(145,167,176,123,150)
largura = c(51,63,64,40,55)
plot(altura, largura)
```

Plotando um dataframe
```{r}
plot(lynx)

plot(lynx, ylab = "Plot com dataframes", xlab="observacoes", col = 'red',
     col.main = 52, cex=1.5)

plot(lynx, main ="Plotando um dataframe" ,ylab = "observacoes", xlab="Periodo", 
     col = 'red', col.main = 52, cex=1.5)
```

Plotando um histograma
```{r}
hist(warpbreaks$breaks)
```

Plotando um boxplot
```{r}
#airquality&lt;-transform(airquality, Month=factor(MOnth)) #transformando a coluna Month em fator
boxplot(Ozone~Month, airquality, xlab = 'Month', ylab='Ozone(ppb)') #plotando o boxplot
```

Parametros usados para plotagem de graficos

```{r}
#col - cor do plotting
#lty - tipo de linha
#lwd - largura da linha
#pch - simbolo do plot
#xlab - label do eixo x
#ylab - label do eixo y
#las - orientacao dos labels
#bg - backgroud color
#mfrow - numero de plots por linha
#mfcol - numero de plots por coluna
```

Funcoes basicas

```{r}
#plots()
#lines()
#points()
#text()
#title()
```

Exemplos
```{r}
par()
par('pch')
par('lty')
```

```{r}
x=2:4
plot(x, pch='c')
```

```{r}
par(mfrow=c(2,2), col.axis='red')
plot(1:8, las='0', xlab = 'xlab', ylab = 'ylab', main = 'LAS 0')
plot(1:8, las='1', xlab = 'xlab', ylab = 'ylab', main = 'LAS 1')
plot(1:8, las='2', xlab = 'xlab', ylab = 'ylab', main = 'LAS 2')
plot(1:8, las='3', xlab = 'xlab', ylab = 'ylab', main = 'LAS 3')
```