---
title: "Matrizes"
author: "Ivanildo Batista"
date: "10 de marco de 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Para criar matrizes usa-se a funcao *matrix()*.

Criando matrizes

```{r}
#por numero de linhas
matrix(c(1,2,3,4,5,6),nr=2) #matriz com 2 linhas
matrix(c(1,2,3,4,5,6),nr=3) #matriz com 3 linhas
matrix(c(1,2,3,4,5,6),nr=6) #matriz com 6 linhas

#por numero de colunas
matrix(c(1,2,3,4,5,6),nc=2) #matriz com 2 colunas
matrix(c(1,2,3,4,5,6),nc=3) #matriz com 3 colunas
matrix(c(1,2,3,4,5,6),nc=6) #matriz com 6 colunas

#nc e nr devem ser multiplos dos numeros de elementos da matriz
```

Criando matrizes com um vetor
```{r}
my_data = c(1:10) #criando um vetor
matrix(data=my_data, nrow = 5, ncol=2, byrow= T) #criando matriz e ordenando 
#os elementos por linha
matrix(data=my_data, nrow = 5, ncol=2, byrow= F) #criando matriz e ordenando
#os elementos por coluna
```

Fatiando uma matriz (ou slicing)

```{r}
mat=matrix(c(2,3,4,5), nr=2)

mat[1,2] #selecionando elemento da linha 1 e da coluna 2
mat[2,2] #selecionando elemento da linha 2 e da coluna 2
#mat[1,3] #selecionando elemento da linha 1 e da coluna 3
mat[,2] #selecionando a coluna 2
```

Criando uma matriz diagonal
```{r}
matriz = 1:3
diag(matriz) #apenas a diagonal tera os valores que foram definidos
```

Extraindo vetor de uma matriz
```{r}
vetor = diag(matriz)
vetor
diag(vetor)
```

Transpor uma matriz
```{r}
W=matrix(c(2,4,8,12), nr=2, ncol=2)
W

t(W)#transposta da matriz
U=t(W)#salvando em uma variavel
U
```

Inversa de uma matriz
```{r}
solve(W)
```

Operacoes com matrizes

```{r}
#criando novas matrizes
mat1 = matrix(c(2,3,4,5), nr = 2)
mat2 = matrix(c(6,7,8,9), nr = 2)

#operações
mat1*mat2 #multiplicando matrizes
mat1/mat2 #divisao entre matrizes
mat1+mat2 #soma de matrizes
mat1-mat2 #subtracao entre matrizes

#multiplicando a matriz por um vetor
x=c(1:4)
x

y= matrix(c(2,3,4,5), nr=2)

y*x
```

Nomeando uma matriz
```{r}
#criando a matriz
mat3 = matrix(c('Futebol','Natacao','Campo','Piscina'), nr=2)

#nomeando as linhas e colunas da matriz
dimnames(mat3) = (list(c('linha1','linha2'),c('coluna1','coluna2')))

mat3

#Identificando linhas e colunas no momento da criacao da matriz

matrix(c(1,2,3,4), nr=2, nc=2, dimnames = list(c('linha1','linha2'),
                                               c('coluna1','coluna2')))
```

Combinando matrizes
```{r}
mat4 = matrix(c(2,3,4,5), nr=2)
mat5 = matrix(c(6,7,8,9), nr=2)

cbind(mat4,mat5) #combinando matrizes por coluna
rbind(mat4, mat5) #combinando matrizes por linha
```

Desconstruindo uma matriz
```{r}
c(mat4) #transforma a coluna em vetor
```