---
title: "Vetores"
author: "Ivanildo Batista"
date: "13 de marco de 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Trabalhando com vetores**

Criando vetores
```{r}
#vetores de caracteres
vetor_caracter = c('Ivanildo','Batista')
vetor_caracter
class(vetor_caracter)#verificando a classe do vetor
```

```{r}
#vetores numericos
vetor_numerico = c(1.8,4.3,300.5)
vetor_numerico
class(vetor_numerico)#verificando a classe do vetor
```

```{r}
#Vetores complexo
vetor_complexo = c(5.2+3i,3.8+4i)
vetor_complexo
class(vetor_complexo)#verificando a classe do vetor
```

```{r}
#vetores logicos
vetor_logico = c(TRUE, FALSE, TRUE, TRUE, FALSE, FALSE)
vetor_logico
class(vetor_logico)#verificando a classe do vetor
```

```{r}
#vetores inteiros
vetor_inteiro = c(2,4,6)
vetor_inteiro
class(vetor_inteiro) #verificando a classe do vetor
```

Utilizando seq() para criar vetores
```{r}
vetor1 = seq(1:10)
vetor1
class(vetor1)#verificando a classe do vetor
```

Utilizando rep() para criar vetores
```{r}
vetor2 = rep(1:10)
vetor2
class(vetor2)#verificando a classe do vetor
```

Indexacao em vetores
```{r}
a = c(1,2,3,4,5)
a
a[1] #verificando valor na posicao 1 no vetor
a[2] #verificando valor na posicao 2 no vetor
a[3] #verificando valor na posicao 3 no vetor
a[4] #verificando valor na posicao 4 no vetor
a[5] #verificando valor na posicao 5 no vetor
a[6] #verificando valor na posicao 6 no vetor
#esse ultimo retornara um valor NA.
```

```{r}
b=c('Ciencia','de','Dados','Economia','Logistica')

b[1] #verificando valor na posicao 1 no vetor
b[2] #verificando valor na posicao 2 no vetor
b[3] #verificando valor na posicao 3 no vetor
b[4] #verificando valor na posicao 4 no vetor
b[5] #verificando valor na posicao 5 no vetor
b[6] #verificando valor na posicao 6 no vetor
#esse ultimo retornara um valor NA.
```

Combinando vetores
```{r}
#usarei os vetores criados anteriomente
c(a,b) #ele transforma os valores numericos em strings
```

Operacao com vetores
```{r}
x = c(24,36,85,54,69)
y = c(3,5,5,8,6)

x*5 #muktiplicando um vetor por uma constante, todos os valores nesse vetor serao
#multiplicados pela constante

x+y #somando vetores, serao somados os valores conforme a indexacao

x-y #subtraindo vetores, serao subtraidos os valores conforme a indexacao

x*y #multiplicando vetores, serao multiplicados os valores conforme a indexacao

x/y #dividindo vetores, serao divididos os valores conforme a indexacao

#somando vetores com quantidades de elementos diferentes
alfa = c(10,20,30)
beta = c(1,2,3,4,5,6,7,8,9)
alfa+beta #somara os valores conforme a indexacao
```

Vetor nomeado
```{r}
v=c('Barack','Obama') #criando um vetor de strings
v #imprimindo o vetor
```

```{r}
names(v) = c('Nome','Sobrenome') #atribundo a cada valor um nome de coluna
v #imprimindo novamente o vetor
v['Nome'] #imprimindo o valor da coluna Nome
v['Sobrenome'] #imprimindo o valor da coluna Sobrenome
```