---
title: "apresentacao familia apply"
author: "Ivanildo Batista da Silva Junior"
date: "25 de maio de 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
vetor1 <- 1:25
matriz = matrix(vetor1, 5,5)
matriz
```
# Apply

```{r}

apply(matriz, 1, sum)

apply(matriz, 2, sum)

apply(mtcars,2,mean)

apply(iris[c('Sepal.Length','Petal.Length')],2,sd)

apply(matriz,1,quantile,probs = c(0.25,0.5,0.75))

vetor_quantiles=c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9)
apply(matriz,1,quantile,probs = vetor_quantiles)
```

# Lapply
```{r}
lista1 = list(a = 1:30, b=c(23,56,89,96,36,25,74), c=rnorm(10))
lista1
```

```{r}
lapply(lista1, sum)

lapply(lista1, var)

lapply(lista1, mean)

lapply(lista1, sd)

lapply(list(iris$Sepal.Length),sum)

lapply(list(iris$Petal.Length),median)

lapply(list(iris$Species),mode)
```


```{r}
#lapply(lista1, runif)
```

#SAPPLY
```{r}

sapply(lista1, sum, simplify = TRUE)

sapply(lista1, sum, simplify = FALSE)
```

```{r}

sapply(lista1, sum, simplify = TRUE)

sapply(lista1, sum, simplify = TRUE, USE.NAMES = lista1$a)

sapply(mtcars[c('mpg','hp')], mean, simplify = TRUE)

sapply(mtcars[c('mpg','hp')], mean, simplify = FALSE)
```

#MAPPLY

```{r}
mapply(prod, 1:2, 1:2, 1:2)

mapply(sum, 1:3,10:12,2:4,7:9)

mapply(rep, 5:8, 4:1)

mapply(function(x, y) {x^y},
       x = c(2,3), y = c(4))

mapply(function(x, y) {x^y},
       x = c(2,3), y = c(4), SIMPLIFY = FALSE)

mapply(function(x, y) {x^y},
       c(2,3), c(3,4,5))

mapply(function(x, y) {x^y},
       c(2,3,4), c(3,4))

mapply(function(x, y) {x^y},
       c(2,3), c(3,4,5,6))

mapply(function(x, y) {x^y},
       c(a = 2, b = 3), c(A = 3, B = 4))

mapply(function(x, y) {x^y},
       c(a = 2, b = 3), c(A = 3, B = 4),
       USE.NAMES = FALSE)

mapply(function(x,y,z,k){(x+k)^(y+z)},
       c(a=2,b=3),c(A=3,B=4),MoreArgs=list(1,2))
```


```{r}

```

#TAPPLY
```{r}
x = 1:40
y = factor(rep(letters[1:8], each = 5))

tapply(x,y,mean)

```



```{r}
tapply(mtcars$mpg,factor(mtcars$cyl),mean)

tapply(mtcars$mpg,factor(mtcars$cyl),median)

tapply(mtcars$mpg,factor(mtcars$cyl),var)

tapply(mtcars$mpg,factor(mtcars$cyl),sd)
```


